# Generated by Django 4.1.7 on 2023-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('ARTC', 'Статья')], default='NEWS', max_length=4),
        ),
    ]
